In [1]:
1+1

2

In [2]:
import numpy as np

In [4]:
n1=np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [5]:
type(n1)

numpy.ndarray

In [6]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
type(n2)

numpy.ndarray

In [9]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [11]:
n2=np.zeros((5,6))

In [12]:
n2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
 n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [14]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
n2=np.arange(10,20,5)
n2

array([10, 15])

In [16]:
n1=np.random.randint(1,100,5)

In [17]:
n1

array([38,  7, 14, 61, 83])

In [21]:
n1=np.array([1,2,3])
n1


array([1, 2, 3])

In [23]:
n1.shape

(3,)

In [24]:
n1=np.array([10,20,30])
n2=np.array([101,210,310])

In [26]:
np.vstack((n1,n2))

array([[ 10,  20,  30],
       [101, 210, 310]])

In [27]:
np.hstack((n1,n2))

array([ 10,  20,  30, 101, 210, 310])

In [28]:
np.column_stack((n1,n2))

array([[ 10, 101],
       [ 20, 210],
       [ 30, 310]])

In [29]:
n1=np.array([10,20,30,40,50,60])
n1=np.array([50,60,70,80,90])

In [30]:
!pip install jedi==0.17.2

   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
    --------------------------------------- 0.0/1.4 MB 1.4 MB/s eta 0:00:02
   - -------------------------------------- 0.1/1.4 MB 656.4 kB/s eta 0:00:03
   --- ------------------------------------ 0.1/1.4 MB 939.4 kB/s eta 0:00:02
   ------- -------------------------------- 0.3/1.4 MB 1.5 MB/s eta 0:00:01
   ---------- ----------------------------- 0.4/1.4 MB 1.7 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.4 MB 1.9 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.4 MB 2.5 MB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.4 MB 2.7 MB/s eta 0:00:01
   ---------------------------------- ----- 1.2/1.4 MB 3.0 MB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 3.0 MB/s eta 0:00:01
   ------------

In [31]:
import pandas as pd

In [32]:
import numpy as np

In [33]:
## Shuvo Kumar Basak

In [34]:
n1=np.array([10,20,30,40,50,60])
n1=np.array([50,60,70,80,90])

In [40]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [41]:
np.setdiff1d(n2,n1)

array([101, 210, 310])

In [42]:
import numpy as np

In [43]:
n1=np.array([10,20])
n2=np.array([30,40])


In [45]:
np.sum([n1,n2])

100

In [46]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [47]:
n1=np.array([10,20])
n2=np.array([30,40])


In [48]:
n1+1

array([11, 21])

In [49]:
n1-1

array([ 9, 19])

In [50]:
n1*5

array([ 50, 100])

In [51]:
n1=np.array([1,2,3,4,5,6,7,8,9])

In [52]:
np.mean(n1)

5.0

In [53]:
np.std(n1)

2.581988897471611

In [54]:
np.median(n1)

5.0

In [55]:
np.save('my_numpy',n1)

In [56]:
n2=np.load('my_numpy.npy')

In [57]:
n2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])